volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:

  frontend:
    image: s418963/foodgram_frontend:latest
    depends_on:
      - backend
    command: sh -c "cp -r /app/build/. /frontend_build/
    volumes:
      - frontend_build:/frontend_build
    restart: "no"

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
      - static:/app/static
      - media:/app/media
      - ../docs:/usr/share/nginx/docs
    depends_on:
      - backend
      - frontend